### ISSUE TITLE
TravisCI considers Go 1.10 in the config to be Go 1.1 when building

### ISSUE THREAD

**Issue by invisiblethreat** [invisiblethreat/duckdns#3]
![image](https://user-images.githubusercontent.com/2525006/46551041-114daa00-c8ad-11e8-8305-371dd2f6c822.png)
This needs to be investigated and remdiated for sanity.

**Comment by theag3nt** [comment]
Do you mind if I take this with me? I see there is already a related pull request, but as I see it doesn't solve the issue.

**Comment by theag3nt** [comment]
Never mind, seeing the failed build I assumed it's still a problem, but after checking the results it's actually because of #4.

**Comment by invisiblethreat** [comment]
All yours!
