### ISSUE TITLE
Unmet dependency for Windows client

### ISSUE THREAD

**Issue by invisiblethreat** [invisiblethreat/duckdns#4]
```
0.12s$ GOOS=windows go build -o duckdns-windows
../../sirupsen/logrus/terminal_windows.go:10:2: cannot find package "github.com/konsorten/go-windows-terminal-sequences" in any of:
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/github.com/konsorten/go-windows-terminal-sequences (from $GOROOT)
	/home/travis/gopath/src/github.com/konsorten/go-windows-terminal-sequences (from $GOPATH)
The command "GOOS=windows go build -o duckdns-windows" exited with 1.
Done. Your build exited with 1.
```

This occurs for all versions of Go. The `logrus` library has been a source of pain since the lower-casing of the repo owner earlier this year. If `vgo` or `dep` solve this more gracefully than `glide` I'm up for that. There's potentially a fix in the `.travis.yml` to be had as the dependency management line is... not robust.

**Comment by theag3nt** [comment]
I'll have a look at this too while sorting out #3.
